Cleanup

diff --git a/deploy/kubernetes/scripts/install b/deploy/kubernetes/scripts/install
--- a/deploy/kubernetes/scripts/install
+++ b/deploy/kubernetes/scripts/install
@@ -19,10 +19,10 @@ die() {
 }
 
 (which kubectl &>/dev/null) || die '* missing kubectl, is it installed?'
-(which bx &>/dev/null) || die '* missing bx, is it installed?'
+#(which bx &>/dev/null) || die '* missing bx, is it installed?'
 (which jq &>/dev/null) || die '* missing jq, is it installed?'
 (which docker &>/dev/null) || die '* missing docker; is it installed?'
-(which mvn &>/dev/null) || die '* missing mvn; is it installed?'
+#(which mvn &>/dev/null) || die '* missing mvn; is it installed?'
 
 if [[ "$#" -eq 0 ]]; then
     echo "$0 [--minikube] [--new-minikube] [--registry REGISTRY] [--tls] [--cassandra] [--build] [--deploy] [--delete] [--nginx] [--all]" >&1
